os: linux
dist: trusty
language: java
jdk:
- openjdk8
install: "/bin/true"
script:
- mvn clean install -q -B
env:
  global:
  - secure: EIAsX8TJvnCAMSACWeTXi1dbL+4VrQRqSZnEdtbPE+/LuFTAWJ5/5wBrBgczZJLVG2RU2xZ3xJ1QDo9wpHpfwVCFn5t99Nal0QzjqUXqTUjFDHDD8dbw2Ju8UJFSzqTuveGiYKVYbcaeWF5DjTOVtA8R3rqQHA+psNyHkCdbJj3ifiDlIhCh4W2lmwH2Y5QAiUDVi8+alJ3/yL1IwYLomEARDjW1XOeiAAVVpuZeeZPIRe+9uoxTrH14QDiJ9N/aBPowoD3Ayj9MBT62HE7RfqnMpqexGObP0S/rqB8vlhGU42b6ZRiHzoxhbDgNRcRq6vue4AVSeB6vWjEkYRVDs7HDtHy1uz5uJ4fD8ENYVSvTyIY3CxVsbpkAOfPw6yVamL7NnytCHgp+Dft9bZlxtKWhveH7NZge6yAtLJWNsIvul4EL5PUVaw5gjq5cuX4E/aQdW7gJsPaiMT0lI4OdkX23GiLfk1G5VDFECqNH67xET+qo+5pzgXONUm9pTAehFHqk44FisyBuo4J6eZy71bMmC/kcebp1YWuAVriiiTtPW8mpgQjAaggE9XuuMqkcIyLhGizrEgKJVqLTUQLyUq8Q4MnoKMWSJuvxFuZe24wXtcH8/QH4fglILbShICYaAhSGCHePiTlMfm9jbTfrqn/5Z2PUi43yWpGuTzFzk3o=
  - secure: MQnaretZJwTHMu40AhnsEyiyvRlapmvxF5ivL0JGkpwl5nP0a2o0bxYRuM7LWbH5P7+MnQNU3D8DIPwqKcWMerUc1aVhy3loQ+IOVuMB1QQNazLMRSMQ7gtRTOQyFHmLfLisvofiLIFzrtpAaLbtLoIUI9rDqYrQLgbY7WvRRzAcD9U/vEW2c3P8PMI3A2D8eva/9/QIWGCy8x2Ohb7ShjJW+jyB6O7d+2PTEdmswHezIXaOVIlOY5KtoM/FPxbLUGXT6OW8KlKFvFOxGJLOMIu8j+ReLgtBJ322OK4g5wrNjqctd6LRLwfXQSn+UmPhe7kqCqttbxG3RflfMcZ98Qblojij8uEYMeG+0kPNeWzu4MXHaCu0sinGJHuoxZp81h82CGGvJ2Mn13Z65puciJg934vOWNzNr3B9xYWFVgusdB0kNDVVI2a8KAzzw6agHlO+s73Uap0aeZgXcoVHsQI+WCBVDC1ABY5l0yrdu5vIxWRNdJM1RYQmcss1g8c+JoTsWGteiBT1xjZF1L3WJy2Cv5pZjflYutLl+h26sWC/QzP/jVKuQ1OQuzC44b2+T07KaqhzPP1sMw1IcleleXq2jDMlEOSzhjR+86Ow3ds1J8vSvB8pX4IR20k7n+PiFpnVTpV4NZ7ddCHshmVpevJqzYvjdYrJff7csuKiTk0=
  - secure: iVMsMdsaLewZGdF8QBcYQPudcuB/+BSGD/lkEa99UHfLHaBmX+mOA75PnGSJMm6hZzYt+o1R10VAM0uvMpl7QZq0vpz9LQgjLW1QaXVlhBtP1C6PYhPHjf29AuYFyWLBKuelvGPlwak8Hy/tqWihWMPlYroNMHj6Ztx8iO6V6Oc5XAlZMryrf7nmgdwlJQXNTH55USzCDzg5AWEIBd6zI7503gFAAUZJwFTt65iDi1QbpShrr/nR3llJ5lfPjFl1R5ahzVufy7gcC4tsqsif4vFIH96pjSOl1ZlMeJHqyD36enwNyR5R73wqW3eSyTOQkpNN2wbZ4j8gwjOJqydvZMCxERzrVKHINSh8S5M9i4+AoYBrMCm8b4mZYQwkLeXLldd12jvAxyVqT2s3oN2lh01dsrAJqgI3CAZZ52WFv5zuNBqkTQEm9Edeg0hU6P329cEtTQNlW3TZ+jJLfNYjQnawIYwgIhsUfv74MPOdgWIH6fonEigPiv2tQ9BOWHy6A0M2E4CGSug8kyb0MXYQ2ZPORHypYui/q2qCEwOoAppL4Mfhzb+PacmnDJGGyzqlCOpCz2dkUx+RZsrKUh20t7tQmPXicUuzK2dP6vY0TFJ3PLdFIghxJ9LVaoRjKEhx97CWKOiIgqTfq9WoHgVyOB104JnPeUQaXhsuF7+27Tk=
  - secure: urVf8qnAu4aRSBiKQgvU/QbmI8zsIiDYKGD9rz1EYmtOsifQ1q9whmtXHtFi/N53/TAUZh+WKzFuyXETb2pp4pGhnKM5nTtmqLf68bcFjaCyhX2XuoYoFp3XI1Uc+MgrkqxMAG5bZtsTL4Y5u5RgoN+Xlkb//zlL7sesUO0NeUq57PKfOwx88rBm/H0qCWPZbIlrg9bKf/Tm4LiiZqCr/XTdEcWcwC5ZeNE82QctAElK3rW3L3z+iPZN016pHA00zbf3xkvjrvBMRyhQykUCJr7lazYvz5kY1BBbESFtb01VR/kTKdnEFSo1zbA0d0QwOsRxnm3xh/wAc53OUfcqQgw2Lcey/n66P0on7EiheaSNnchxMnlCpBwD8j01eNQKiCiblDB4rrollD3h8AkNp9zxiBFhTUrQw2Gbp3jrXKHPSFb2ki8xBQz9QMjunhnVExOy/NY14GEZP4mI2KFXL7TMkHjxL4CDh/bMKG1hzSNLuSahJBlMRXqA7RdJPyo8QXZKjnLDVVxyQgz5Iie1Cafqr5D83Gy60U2929D8Oy0qsayc4w1vbubS+xbdSZ7sBz9VQSNkTTDnLVyxCiX2hM+K5Iwi85jeY677znqrNijMsCB3IsD+UxizN+8NO9YTG7tKzG0n8i0fgjCa+Uryqt/o4CRYsawuCk85zmtm7Ug=
before_deploy: 
- openssl aes-256-cbc -K $encrypted_90984af4e782_key -iv $encrypted_90984af4e782_iv
  -in .travis/gpg.asc.enc -out .travis/gpg.asc -d
deploy:
- skip_cleanup: true
  provider: script
  script: chmod +x ./deploy.sh && ./deploy.sh
  on:
    branch: master
- skip_cleanup: true
  provider: script
  script: chmod +x ./deploy.sh && ./deploy.sh
  on:
    tags: true
after_success:
- bash <(curl -s https://codecov.io/bash) -t 125b5cce-e4ad-461d-9384-b383e435ccb5
